"use client";
import { Footer, Navbar } from "@/components";
import "./globals.css";
import { QueryClientProvider, QueryClient } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";
import { ContextProvider } from "@/context/Context";

export const metadata = {
  title: "MyTube",
  description: "Generated by create next app",
};

const client = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Andika:ital@1&family=Inter:wght@500&family=Open+Sans&family=Poppins&display=swap" rel="stylesheet" />
      </head>
      <body suppressHydrationWarning={true}>
        <Navbar />
        <ContextProvider>
          <QueryClientProvider client={client}>
            {children}
            <ReactQueryDevtools />
          </QueryClientProvider>
        </ContextProvider>
        <Footer />
      </body>
    </html>
  );
}
